# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

image: Visual Studio 2017
platform:
  - x64

cache:
  # - windows\nsis-plugins\bin
  # - windows\windns\bin
  # - windows\winfw\bin
  # - windows\winroute\bin
  # - .mtime_cache

environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    CPP_BUILD_TARGETS: "x64"
    RUST_BACKTRACE: "1"
    CPP_BUILD_MODES: "Debug"
    OPENSSL_STATIC: "1"

  matrix:
    - RUST_VERSION: 1.33.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc --print cfg
  - rustc -Vv
  - cargo -Vv
  - git submodule update --init
  - ruby ci/mtime_cache windows/**/*.{cpp,h} --verbose --cache .mtime_cache/cache.json

# This is the "test phase", tweak it as you see fit
test_script:
  - ps: . .\env.ps1
  - bash -x build_windows_modules.sh --dev-build
  - cargo build
  - cargo test

# Stops feature branches from triggering two builds (One for branch and one for PR)
skip_branch_with_pr: true

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

# We build in the test stage, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false
